#
# Makefile for pong
# so jenkins can build this


CPP= g++
SDL_LIB = -I /SDL/include/
CPPFLAGS = -O0 -g3 -Wall 

Entity.o:	Entity.cpp Entity.h
	$(CPP) $(SDL_LIB) $(CPPFLAGS) -c -o Entity.o Entity.cpp
